export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const UPDATE_CART_PRODUCT = "UPDATE_CART_PRODUCT";
export const CLEAR_CART = "CLEAR_CART";
